[package]
name = "kps"
version = "0.1.0"
authors = ["Leandro Peralta <leandro.peralta@trademe.co.nz>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"
pancurses = "0.16"